### ISSUE TITLE
Error to Build on Ubuntu 24.04

### ISSUE THREAD

**Issue by Hygens** [maxence-charriere/go-app#1022]
I have that error building one sample app with:

 <pre>
Ubuntu 24.04: 6.1.0-1025-rockchip #25-Ubuntu SMP Mon Aug 26 23:01:14 UTC 2024 aarch64 aarch64 aarch64 GNU/Linux
go version:  go1.23.5 linux/arm64

jose@jose-opi5max:~/go/src/go_app_sample$ make build
GOARCH=wasm GOOS=js go build -o web/app.wasm
# github.com/google/uuid
../../pkg/mod/github.com/google/uuid@v1.6.0/uuid.go:89:18: undefined: xtob
../../pkg/mod/github.com/google/uuid@v1.6.0/uuid.go:110:12: undefined: xtob
../../pkg/mod/github.com/google/uuid@v1.6.0/uuid.go:134:20: undefined: xtob
../../pkg/mod/github.com/google/uuid@v1.6.0/uuid.go:155:12: undefined: xtob
../../pkg/mod/github.com/google/uuid@v1.6.0/uuid.go:177:13: uuid.UnmarshalBinary undefined (type UUID has no field or method UnmarshalBinary)
../../pkg/mod/github.com/google/uuid@v1.6.0/uuid.go:217:13: undefined: xtob
../../pkg/mod/github.com/google/uuid@v1.6.0/uuid.go:233:16: undefined: xtob
../../pkg/mod/github.com/google/uuid@v1.6.0/time.go:100:3: undefined: randomBits
../../pkg/mod/github.com/google/uuid@v1.6.0/version6.go:48:2: undefined: nodeMu
../../pkg/mod/github.com/google/uuid@v1.6.0/version6.go:49:5: undefined: nodeID
../../pkg/mod/github.com/google/uuid@v1.6.0/version6.go:49:5: too many errors
make: *** [Makefile:2: build] Error 1
</pre>
 
For while I reverted to go 1.21.13 and work in that version.

**Comment by Hygens** [comment]
I have solved that erasing all go configs and folders, uninstalling go, after reinstall go latest.
No more problems.
