### ISSUE TITLE
Migrate From V6 to V9

### ISSUE THREAD

**Issue by suntong** [maxence-charriere/go-app#870]
I was looking for migration guide but only found [this](https://go-app.dev/migrate), IE, from V8 to V9.

Following up on #869, I'm getting the following errors when migrating from V6 to V9:

```
undefined: app.Navigate
undefined: app.NewContextMenu
undefined: app.MenuItem
undefined: app.Reload
too many errors
```

and maybe more as I got `too many errors` at the end.

The reason I'm doing this is that I found a bunch of good go-app demos, but all in V6, like  
https://github.com/maxence-charriere/go-app-demo/blob/v6/demo/server/main.go
and I was trying to make use of them in V9, but now it seems to be beyond me thus I'm asking for help.

**Comment by suntong** [comment]
- `app.Navigate` is fixed (#869)
- `app.Reload` can be fixed same way (to `ctx.Reload`)

However, for `app.MenuItem` and `app.NewContextMenu`, I didn't find anything that is close in https://go-app.dev/reference
